/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SM;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thilona
 */
public class UDNonOverlapping extends javax.swing.JFrame {

    String nonoverlappingid = "";
    private int xAxisMousePoint;
    private int yAxisMousePoint;

    /**
     * Creates new form UDConsecutive
     */
  
    public UDNonOverlapping() {
        initComponents();
        loadTableData();
        loadSubjects();
    }
    
    
        protected void setMouseClickedLocation(int x, int y) {
        this.xAxisMousePoint = x;
        this.yAxisMousePoint = y;
    }
     protected void setWindowLocation(int x, int y) {
        this.setLocation(x - xAxisMousePoint, y - yAxisMousePoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTopBar = new javax.swing.JPanel();
        btn_Exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        osubject1 = new javax.swing.JComboBox<>();
        osubject2 = new javax.swing.JComboBox<>();
        osubject4 = new javax.swing.JComboBox<>();
        osubject3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowTopBar.setBackground(new java.awt.Color(255, 255, 255));
        windowTopBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        windowTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowTopBarMouseDragged(evt);
            }
        });
        windowTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowTopBarMousePressed(evt);
            }
        });
        windowTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit1.setBorder(null);
        btn_Exit1.setBorderPainted(false);
        btn_Exit1.setContentAreaFilled(false);
        btn_Exit1.setFocusPainted(false);
        btn_Exit1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_2.png"))); // NOI18N
        btn_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit1ActionPerformed(evt);
            }
        });
        windowTopBar.add(btn_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 0, 34, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Update And Delete Non Overlapping Sessions");
        windowTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, 20));

        getContentPane().add(windowTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 476, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 476, 140, -1));

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 476, 140, -1));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setBorderPainted(false);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setFocusPainted(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_2.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 0, 34, -1));

        osubject1.setEditable(true);
        osubject1.setFocusable(false);
        jPanel1.add(osubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 181, -1));

        osubject2.setEditable(true);
        osubject2.setFocusable(false);
        jPanel1.add(osubject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 181, -1));

        osubject4.setEditable(true);
        osubject4.setFocusable(false);
        jPanel1.add(osubject4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 183, -1));

        osubject3.setEditable(true);
        osubject3.setFocusable(false);
        jPanel1.add(osubject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 183, -1));

        jLabel2.setText("Subject 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel3.setText("Subject 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel4.setText("Subject 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jLabel5.setText("Subject 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Subject 1", "Subject 2", "Subject 3", "Subject 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 572, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if (selectedRow != -1) {
            osubject1.setSelectedItem(dtm.getValueAt(selectedRow, 1).toString());
            osubject2.setSelectedItem(dtm.getValueAt(selectedRow, 2).toString());
            osubject3.setSelectedItem(dtm.getValueAt(selectedRow, 3).toString());
            osubject4.setSelectedItem(dtm.getValueAt(selectedRow, 4).toString());
            nonoverlappingid = dtm.getValueAt(selectedRow, 0).toString();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                if (osubject1.getSelectedItem().toString().equals("<-Select->")) {
                    JOptionPane.showMessageDialog(rootPane, "Select the subject 1");
                } else if (osubject2.getSelectedItem().toString().equals("<-Select->")) {
                    JOptionPane.showMessageDialog(rootPane, "Select the subject 2");
                } else if (osubject3.getSelectedItem().toString().equals("<-Select->")) {
                    JOptionPane.showMessageDialog(rootPane, "Select the subject 3");
                } else if (osubject4.getSelectedItem().toString().equals("<-Select->")) {
                    JOptionPane.showMessageDialog(rootPane, "Select the subject 4");
                } else {
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    String subject1 = osubject1.getSelectedItem().toString();
                    String subject2 = osubject2.getSelectedItem().toString();
                    String subject3 = osubject3.getSelectedItem().toString();
                    String subject4 = osubject4.getSelectedItem().toString();
                    String subject1id = "";
                    String subject2id = "";
                    String subject3id = "";
                    String subject4id = "";
                    ResultSet rs1 = DB.DB.search("select idsubjects from subjects where name='" + subject1 + "'");
                    if (rs1.first()) {
                        subject1id = rs1.getString(1);
                    }
                    ResultSet rs2 = DB.DB.search("select idsubjects from subjects where name='" + subject2 + "'");
                    if (rs2.first()) {
                        subject2id = rs2.getString(1);
                    }
                    ResultSet rs3 = DB.DB.search("select idsubjects from subjects where name='" + subject3 + "'");
                    if (rs3.first()) {
                        subject3id = rs3.getString(1);
                    }
                    ResultSet rs4 = DB.DB.search("select idsubjects from subjects where name='" + subject4 + "'");
                    if (rs4.first()) {
                        subject4id = rs4.getString(1);
                    }
                    DB.DB.iud("update non_overlapping set subjects1='" + subject1id + "', subjects2='" + subject2id + "', subjects3='" + subject3id + "', subjects4='" + subject4id + "' where idnon_overlapping='" + nonoverlappingid + "'");
                    JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
                    loadTableData();
                    clearFields();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteSession();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_Exit1ActionPerformed

    private void windowTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMouseDragged
        this.setWindowLocation(evt.getXOnScreen(), evt.getYOnScreen());
    }//GEN-LAST:event_windowTopBarMouseDragged

    private void windowTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMousePressed
        this.setMouseClickedLocation(evt.getX(), evt.getY());
    }//GEN-LAST:event_windowTopBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UDNonOverlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UDNonOverlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UDNonOverlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UDNonOverlapping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UDNonOverlapping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Exit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> osubject1;
    private javax.swing.JComboBox<String> osubject2;
    private javax.swing.JComboBox<String> osubject3;
    private javax.swing.JComboBox<String> osubject4;
    private javax.swing.JPanel windowTopBar;
    // End of variables declaration//GEN-END:variables

    private void loadSubjects() {
        try {
            osubject1.addItem("<-Select->");
            osubject2.addItem("<-Select->");
            osubject3.addItem("<-Select->");
            osubject4.addItem("<-Select->");
            ResultSet rs = DB.DB.search("select distinct name from subjects");
            while (rs.next()) {
                osubject1.addItem(rs.getString(1));
                osubject2.addItem(rs.getString(1));
                osubject3.addItem(rs.getString(1));
                osubject4.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadTableData() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.DB.search("select no.idnon_overlapping,s1.name,s2.name,s3.name,s4.name from non_overlapping no join subjects s1 on no.subjects1=s1.idsubjects join subjects s2 on no.subjects2=s2.idsubjects join subjects s3 on no.subjects3=s3.idsubjects join subjects s4 on no.subjects4=s4.idsubjects where no.status!='deactive'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void deleteSession() {
        try {
            DB.DB.iud("update non_overlapping set status='deactive' where idnon_overlapping='" + nonoverlappingid + "'");
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTableData();
            clearFields();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        osubject1.setSelectedItem("<-Select->");
        osubject2.setSelectedItem("<-Select->");
        osubject3.setSelectedItem("<-Select->");
        osubject4.setSelectedItem("<-Select->");
    }
}
