/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RM;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thilona
 */
public class ManageRooms extends javax.swing.JFrame {

    String locationid="";
    private int xAxisMousePoint;
    private int yAxisMousePoint;
    /**
     * Creates new form ManageRooms
     */
    
    
    public ManageRooms() {
        initComponents();
        loadTableData();
    }
    
      
        protected void setMouseClickedLocation(int x, int y) {
        this.xAxisMousePoint = x;
        this.yAxisMousePoint = y;
    }
     protected void setWindowLocation(int x, int y) {
        this.setLocation(x - xAxisMousePoint, y - yAxisMousePoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lab = new javax.swing.JRadioButton();
        rcapacity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        rname = new javax.swing.JTextField();
        lhall = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        windowTopBar = new javax.swing.JPanel();
        btn_Exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Building", "Room", "Room Type", "Capacity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 580, 152));

        lab.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(lab);
        lab.setText("Laboratory");
        getContentPane().add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 291, -1, -1));
        getContentPane().add(rcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 332, 169, -1));

        jLabel2.setText("Building Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));

        jLabel3.setText("Room Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, 66, -1));

        jLabel4.setText("Room Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 295, 66, -1));

        jLabel5.setText("Capacity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 335, 66, -1));
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 294, 174, -1));
        getContentPane().add(rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 332, 174, -1));

        lhall.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(lhall);
        lhall.setSelected(true);
        lhall.setText("Lecture Hall");
        getContentPane().add(lhall, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 291, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowTopBar.setBackground(new java.awt.Color(255, 255, 255));
        windowTopBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        windowTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowTopBarMouseDragged(evt);
            }
        });
        windowTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowTopBarMousePressed(evt);
            }
        });
        windowTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit1.setBorder(null);
        btn_Exit1.setBorderPainted(false);
        btn_Exit1.setContentAreaFilled(false);
        btn_Exit1.setFocusPainted(false);
        btn_Exit1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_2.png"))); // NOI18N
        btn_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit1ActionPerformed(evt);
            }
        });
        windowTopBar.add(btn_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 0, 34, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Locations");
        windowTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, 20));

        jPanel2.add(windowTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 140, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 150, -1));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearFields();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            if (dtm.getValueAt(selectedRow, 3).toString().equals("Lecture Hall")) {
                lhall.setSelected(true);
            } else {
                lab.setSelected(true);
            }
            bname.setText(dtm.getValueAt(selectedRow, 1).toString());
            rname.setText(dtm.getValueAt(selectedRow, 2).toString());
            rcapacity.setText(dtm.getValueAt(selectedRow, 4).toString());
            locationid = dtm.getValueAt(selectedRow, 0).toString();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (bname.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Building name is empty");
            } else if (rname.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Romm Name is empty");
            } else if (rcapacity.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Capacity is empty");
            } else {
                String building = bname.getText();
                 String room = rname.getText();
                 String capacity = rcapacity.getText();
                 String roomtype="";
                 if (lhall.isSelected()) {
                     roomtype="Lecture Hall";
                 }else{
                     roomtype="Laboratory";
                 }
                 DB.DB.iud("update building set name='"+building+"' , room_name='"+room+"', type='"+roomtype+"', capacity='"+capacity+"' where idbuilding='"+locationid+"' ");
                 JOptionPane.showMessageDialog(rootPane, "Succesfully updated");
                 clearFields();
                 loadTableData();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deleteRooms();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_Exit1ActionPerformed

    private void windowTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMouseDragged
        this.setWindowLocation(evt.getXOnScreen(), evt.getYOnScreen());
    }//GEN-LAST:event_windowTopBarMouseDragged

    private void windowTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMousePressed
        this.setMouseClickedLocation(evt.getX(), evt.getY());
    }//GEN-LAST:event_windowTopBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bname;
    private javax.swing.JButton btn_Exit1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lab;
    private javax.swing.JRadioButton lhall;
    private javax.swing.JTextField rcapacity;
    private javax.swing.JTextField rname;
    private javax.swing.JPanel windowTopBar;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.DB.search("select * from building where status!='deactive'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        bname.setText("");
        rname.setText("");
        rcapacity.setText("");
        lhall.setSelected(true);
//        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//        dtm.setRowCount(0);
    }

    private void deleteRooms() {
       try {
            DB.DB.iud("update building set status='deactive' where idbuilding='" + locationid + "'");
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTableData();
            clearFields();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
