/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import Group.TimeTable;
import HM.ManageNotAvailableRoom;
import HM.WorkingDaysHours;
import LM.AddLecturer;
import LM.AddSession;
import LM.AddSubject;
import RM.AddRooms;
import RM.AddSessionRooms;
import SM.AddTags;
import SM.SesssionAllocation;
import SM.addSgroups;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PLEX
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
  

    MainWindow() {
        super();
        initComponents();
        setExtendedState(MainWindow.MAXIMIZED_BOTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        windowTopBar = new javax.swing.JPanel();
        btn_Minimize = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 90, 101));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SA1.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SA_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASG_1.png"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASG_2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AL_1.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AL_2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 300, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AS_1.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AS_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASub_1.png"))); // NOI18N
        jButton5.setText("jButton1");
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASub_2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 300, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/GT_1.png"))); // NOI18N
        jButton6.setText("jButton1");
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/GT_2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, 50));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AR_1.png"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AR-2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 300, 50));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASR_1.png"))); // NOI18N
        jButton8.setText("jButton1");
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ASR_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 300, 50));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MNAR_1.png"))); // NOI18N
        jButton9.setText("jButton1");
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MNAR_2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 300, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AWDH_1.png"))); // NOI18N
        jButton10.setText("jButton1");
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AWDH_2.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 300, 50));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Add_tag_1.png"))); // NOI18N
        jButton11.setText("jButton1");
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Add_tag_2.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 770));

        windowTopBar.setBackground(new java.awt.Color(252, 252, 252));
        windowTopBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        windowTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowTopBarMouseDragged(evt);
            }
        });
        windowTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowTopBarMousePressed(evt);
            }
        });
        windowTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize1.png"))); // NOI18N
        btn_Minimize.setBorder(null);
        btn_Minimize.setBorderPainted(false);
        btn_Minimize.setContentAreaFilled(false);
        btn_Minimize.setFocusPainted(false);
        btn_Minimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize2.png"))); // NOI18N
        btn_Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinimizeActionPerformed(evt);
            }
        });
        windowTopBar.add(btn_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 40));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setBorderPainted(false);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setFocusPainted(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_2.png"))); // NOI18N
        btn_Exit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        windowTopBar.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 121, 167));
        jLabel1.setText("Time Table Management System");
        windowTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 20));

        getContentPane().add(windowTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1050, 40));

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setMaximumSize(new java.awt.Dimension(1050, 730));
        view.setMinimumSize(new java.awt.Dimension(1050, 730));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/main.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Path 170.png"))); // NOI18N

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 1050, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMousePressed
      
    }//GEN-LAST:event_windowTopBarMousePressed

    private void windowTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMouseDragged
    
    }//GEN-LAST:event_windowTopBarMouseDragged

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

        System.exit(WIDTH);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addSgroups cus = new addSgroups(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) cus.Add_Sgroup);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SesssionAllocation sa = new SesssionAllocation(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) sa.SA);      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        AddTags at = new AddTags(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) at.AT); 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AddLecturer at = new AddLecturer(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) at.AddLec); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AddSession at = new AddSession(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) at.AddSess); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AddSubject at = new AddSubject(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) at.AddSub); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TimeTable gt = new TimeTable(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) gt.GT); 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AddRooms ar = new AddRooms(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) ar.AR); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AddSessionRooms asr = new AddSessionRooms(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) asr.AddSR); 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ManageNotAvailableRoom mnr = new ManageNotAvailableRoom(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) mnr.MNAR); 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        WorkingDaysHours wdg = new WorkingDaysHours(this);
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) wdg.AWD); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btn_MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinimizeActionPerformed
        setExtendedState(MainWindow.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Minimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public final javax.swing.JPanel view = new javax.swing.JPanel();
    private javax.swing.JPanel windowTopBar;
    // End of variables declaration//GEN-END:variables

  

  

    private void changeCursor() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

}
