/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LM;

import Main.MainWindow;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Thilona
 */
public class AddSession extends javax.swing.JFrame {

    /**
     * Creates new form AddSession
     */
      private MainWindow mainWindow;

  
    public AddSession(MainWindow mainWindow) {
        initComponents();
        loadLecturer();
        loadTag();
        loadGroup();
        loadSubject();
        this.mainWindow = mainWindow;
        
    }
    
    public AddSession() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scode = new javax.swing.JTextField();
        ssubject = new javax.swing.JComboBox<>();
        stag = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slecture = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sgroup = new javax.swing.JComboBox<>();
        sduration = new javax.swing.JTextField();
        snoofstd = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddSess.setBackground(new java.awt.Color(255, 255, 255));
        AddSess.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Session");
        AddSess.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select Tag");
        AddSess.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 140, 40));

        scode.setEditable(false);
        AddSess.add(scode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 330, 40));

        ssubject.setEditable(true);
        ssubject.setFocusable(false);
        ssubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubjectActionPerformed(evt);
            }
        });
        AddSess.add(ssubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 330, 40));

        stag.setEditable(true);
        stag.setFocusable(false);
        AddSess.add(stag, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 330, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Duration");
        AddSess.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("No Of Students");
        AddSess.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Subject Code");
        AddSess.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Select Subject");
        AddSess.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 140, 40));

        slecture.setEditable(true);
        slecture.setFocusable(false);
        AddSess.add(slecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 330, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Select Group");
        AddSess.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Lecturer");
        AddSess.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 40));

        sgroup.setEditable(true);
        sgroup.setFocusable(false);
        AddSess.add(sgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 330, 40));
        AddSess.add(sduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 330, 40));
        AddSess.add(snoofstd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 330, 40));

        clear.setBackground(java.awt.Color.red);
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorderPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        AddSess.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 190, 40));

        submit.setBackground(new java.awt.Color(0, 204, 255));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Save");
        submit.setBorderPainted(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        AddSess.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 190, 40));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddSess.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 190, 40));

        getContentPane().add(AddSess, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearFields();
    }//GEN-LAST:event_clearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            if (slecture.getSelectedItem().toString().equals("<-Select->")) {
                JOptionPane.showMessageDialog(rootPane, "Select the lecturer");
            } else if (stag.getSelectedItem().toString().equals("<-Select->")) {
                JOptionPane.showMessageDialog(rootPane, "Select the tag");
            } else if (sgroup.getSelectedItem().toString().equals("<-Select->")) {
                JOptionPane.showMessageDialog(rootPane, "Select the group");
            } else if (ssubject.getSelectedItem().toString().equals("<-Select->")) {
                JOptionPane.showMessageDialog(rootPane, "Select the subject");
            } else if (scode.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Subject code is empty");
            } else if (snoofstd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "No of students is empty");
            } else if (sduration.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Duration is empty");
            } else {
                String lecturer = slecture.getSelectedItem().toString();
                String tag = stag.getSelectedItem().toString();
                String group = sgroup.getSelectedItem().toString();
                String subject = ssubject.getSelectedItem().toString();
                String lecturerid = "";
                String tagid = "";
                String groupid = "";
                String subjectid = "";
                ResultSet rs1 = DB.DB.search("select idlecturer from lecturer where name='" + lecturer + "'");
                if (rs1.first()) {
                    lecturerid = rs1.getString(1);
                }
                ResultSet rs2 = DB.DB.search("select idtags from tags where name='" + tag + "'");
                if (rs2.first()) {
                    tagid = rs2.getString(1);
                }
                ResultSet rs3 = DB.DB.search("select idstudent_groups from student_groups where groups_id='" + group + "'");
                if (rs3.first()) {
                    groupid = rs3.getString(1);
                }

                ResultSet rs4 = DB.DB.search("select idsubjects from subjects where name='" + subject + "'");
                if (rs4.first()) {
                    subjectid = rs4.getString(1);
                }

                DB.DB.iud("insert into lecture_sessions (subject_code, std_count, duration, lecturer_id, subjects_id, tags_id, group_id,status) values ('" + scode.getText() + "','" + snoofstd.getText() + "','" + sduration.getText() + "','" + lecturerid + "','" + subjectid + "','" + tagid + "','" + groupid + "', 'Active')");
                JOptionPane.showMessageDialog(rootPane, "Successfully Saved");
                clearFields();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitActionPerformed

    private void ssubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubjectActionPerformed
        if (ssubject.getSelectedItem() != null) {
            try {
                ResultSet rs = DB.DB.search("select code from subjects where name='" + ssubject.getSelectedItem().toString() + "'");
                while (rs.next()) {
                    scode.setText(rs.getString(1));
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_ssubjectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManageSession ud = new ManageSession();
        ud.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddSession().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JPanel AddSess = new javax.swing.JPanel();
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField scode;
    private javax.swing.JTextField sduration;
    private javax.swing.JComboBox<String> sgroup;
    private javax.swing.JComboBox<String> slecture;
    private javax.swing.JTextField snoofstd;
    private javax.swing.JComboBox<String> ssubject;
    private javax.swing.JComboBox<String> stag;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private void loadLecturer() {
        try {
            slecture.addItem("<-Select->");
            ResultSet rs = DB.DB.search("select distinct name from lecturer");
            while (rs.next()) {
                slecture.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadTag() {
        try {
            stag.addItem("<-Select->");
            ResultSet rs = DB.DB.search("select distinct name from tags");
            while (rs.next()) {
                stag.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadGroup() {
        try {
            sgroup.addItem("<-Select->");
            ResultSet rs = DB.DB.search("select distinct groups_id from student_groups");
            while (rs.next()) {
                sgroup.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadSubject() {
        try {
            ssubject.addItem("<-Select->");
            ResultSet rs = DB.DB.search("select distinct name from subjects");
            while (rs.next()) {
                ssubject.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void clearFields() {
        scode.setText("");
        snoofstd.setText("");
        sduration.setText("");
    }
}
