/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LM;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thilona
 */
public class ManageSubject extends javax.swing.JFrame {

    String subjectid = "";
    private int xAxisMousePoint;
    private int yAxisMousePoint;

    /**
     * Creates new form ManageSubject
     */
    public ManageSubject() {
        initComponents();
        loadTableData();
    }
    
        protected void setMouseClickedLocation(int x, int y) {
        this.xAxisMousePoint = x;
        this.yAxisMousePoint = y;
    }
     protected void setWindowLocation(int x, int y) {
        this.setLocation(x - xAxisMousePoint, y - yAxisMousePoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ssecondsem = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        sfirstsem = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        scode = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        sofferyear = new javax.swing.JComboBox<>();
        sevoh = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        slabh = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        stutorialh = new javax.swing.JSpinner();
        slech = new javax.swing.JSpinner();
        windowTopBar = new javax.swing.JPanel();
        btn_Exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Subject Name", "Subject Code", "Offered Year", "Offered Semester", "Lec Hours", "Totorial Hours", "Lab Hours", "Evolution Hours"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 155));

        jLabel4.setText("Subject Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 344, -1, -1));

        ssecondsem.setBackground(new java.awt.Color(255, 255, 255));
        ssecondsem.setText("Second");
        getContentPane().add(ssecondsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 300, -1, -1));

        jLabel3.setText("Offered Semester");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 304, -1, -1));

        sfirstsem.setBackground(new java.awt.Color(255, 255, 255));
        sfirstsem.setSelected(true);
        sfirstsem.setText("First");
        getContentPane().add(sfirstsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 300, -1, -1));

        jLabel2.setText("Offered Year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 265, -1, -1));
        getContentPane().add(scode, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 379, 139, -1));
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 341, 139, -1));

        sofferyear.setEditable(true);
        sofferyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        sofferyear.setFocusable(false);
        getContentPane().add(sofferyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 262, 139, -1));
        getContentPane().add(sevoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 379, 50, -1));

        jLabel9.setText("Number of Ecolution Hours");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 382, -1, -1));

        jLabel8.setText("Number of Lab Hours");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 344, -1, -1));
        getContentPane().add(slabh, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 341, 50, -1));

        jLabel7.setText("Number of Tutorial Hours");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 304, -1, -1));

        jLabel6.setText("Number of Lecture Hours");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 265, -1, -1));

        jLabel5.setText("Subject Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 382, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setBackground(java.awt.Color.red);
        delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 110, -1));

        update.setBackground(new java.awt.Color(0, 153, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 110, -1));
        jPanel1.add(stutorialh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 50, -1));
        jPanel1.add(slech, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 50, -1));

        windowTopBar.setBackground(new java.awt.Color(255, 255, 255));
        windowTopBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        windowTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowTopBarMouseDragged(evt);
            }
        });
        windowTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowTopBarMousePressed(evt);
            }
        });
        windowTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_1.png"))); // NOI18N
        btn_Exit1.setBorder(null);
        btn_Exit1.setBorderPainted(false);
        btn_Exit1.setContentAreaFilled(false);
        btn_Exit1.setFocusPainted(false);
        btn_Exit1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close_2.png"))); // NOI18N
        btn_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit1ActionPerformed(evt);
            }
        });
        windowTopBar.add(btn_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 0, 34, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Subjects");
        windowTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, 20));

        jPanel1.add(windowTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            if (scode.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Subject code is empty");
            } else if (sname.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Subject Name is empty");
            } else {
                String offeryear = sofferyear.getSelectedItem().toString();
                String semester = "";
                if (sfirstsem.isSelected()) {
                    semester = "First";
                } else {
                    semester = "Second";
                }
                String subject = sname.getText();
                String code = scode.getText();
                String lechours = slech.getValue().toString();
                String tutorialhours = stutorialh.getValue().toString();
                String labhours = slabh.getValue().toString();
                String evolutionhours = sevoh.getValue().toString();
                DB.DB.iud("update subjects set name='" + subject + "', code='" + code + "', semester='" + semester + "', lecture_hours='" + lechours + "', lab_hours='" + labhours + "', totorial_hours='" + tutorialhours + "', evolution_hours='" + evolutionhours + "', year='" + offeryear + "' where idsubjects='" + subjectid + "'");
                JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
                loadTableData();
                clearFields();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            sofferyear.setSelectedItem(dtm.getValueAt(selectedRow, 3).toString());
            if (dtm.getValueAt(selectedRow, 4).toString().equals("First")) {
                sfirstsem.setSelected(true);
            } else {
                ssecondsem.setSelected(false);
            }
            sname.setText(dtm.getValueAt(selectedRow, 1).toString());
            scode.setText(dtm.getValueAt(selectedRow, 2).toString());
            slech.setValue(Integer.parseInt(dtm.getValueAt(selectedRow, 5).toString()));
            stutorialh.setValue(Integer.parseInt(dtm.getValueAt(selectedRow, 6).toString()));
            slabh.setValue(Integer.parseInt(dtm.getValueAt(selectedRow, 7).toString()));
            sevoh.setValue(Integer.parseInt(dtm.getValueAt(selectedRow, 8).toString()));
            subjectid = dtm.getValueAt(selectedRow, 0).toString();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        deleteSubject();
    }//GEN-LAST:event_deleteActionPerformed

    private void btn_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_Exit1ActionPerformed

    private void windowTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMouseDragged
        this.setWindowLocation(evt.getXOnScreen(), evt.getYOnScreen());
    }//GEN-LAST:event_windowTopBarMouseDragged

    private void windowTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowTopBarMousePressed
        this.setMouseClickedLocation(evt.getX(), evt.getY());
    }//GEN-LAST:event_windowTopBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit1;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField scode;
    private javax.swing.JSpinner sevoh;
    private javax.swing.JRadioButton sfirstsem;
    private javax.swing.JSpinner slabh;
    private javax.swing.JSpinner slech;
    private javax.swing.JTextField sname;
    private javax.swing.JComboBox<String> sofferyear;
    private javax.swing.JRadioButton ssecondsem;
    private javax.swing.JSpinner stutorialh;
    private javax.swing.JButton update;
    private javax.swing.JPanel windowTopBar;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        sname.setText("");
        scode.setText("");
        slech.setValue(0);
        stutorialh.setValue(0);
        slabh.setValue(0);
        sevoh.setValue(0);
    }

    private void loadTableData() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.DB.search("select s.idsubjects,s.name,s.code,s.year,s.semester,s.lecture_hours,s.totorial_hours,s.lab_hours,s.evolution_hours from subjects s where s.status!='deactive'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void deleteSubject() {
        try {
            DB.DB.iud("update subjects set status='deactive' where idsubjects='" + subjectid + "'");
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTableData();
            clearFields();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
