/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LM;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thilona
 */
public class Managelecturers extends javax.swing.JFrame {

    String lecid="";
    /**
     * Creates new form Managelecturers
     */
    public Managelecturers() {
        initComponents();
        loadFaculty();
        loadCampus();
        loadLevel();
        loadDepartment();
        loadBuilding();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lempid = new javax.swing.JTextField();
        llevel = new javax.swing.JComboBox<>();
        lfaculty = new javax.swing.JComboBox<>();
        lecname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lrank = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbuilding = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ldep = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lcampus = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Lecturers");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Employee ID", "Faculty", "Department", "Campus", "Building", "Level", "Rank"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Faculty");

        jLabel9.setText("Rank");

        jLabel8.setText(" Building");

        jLabel7.setText("Department");

        jLabel6.setText("Employee ID");

        lrank.setEditable(false);

        jLabel5.setText("Level");

        jLabel4.setText("Campus");

        jLabel2.setText("Lecturer Name");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lecname)
                                    .addComponent(lfaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lcampus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(llevel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lempid))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(delete)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(ldep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbuilding, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lrank)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(update)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(lecname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(lfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(lcampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(llevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(delete))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        if (selectedRow!=-1) {
            lecname.setText(dtm.getValueAt(selectedRow, 1).toString());
            lfaculty.setSelectedItem(dtm.getValueAt(selectedRow, 3).toString());
            lcampus.setSelectedItem(dtm.getValueAt(selectedRow, 5).toString());
            llevel.setSelectedItem(dtm.getValueAt(selectedRow, 7).toString());
            lempid.setText(dtm.getValueAt(selectedRow, 2).toString());
            ldep.setSelectedItem(dtm.getValueAt(selectedRow, 4).toString());
            lbuilding.setSelectedItem(dtm.getValueAt(selectedRow, 6).toString());
            lrank.setText(dtm.getValueAt(selectedRow, 8).toString());
            lecid=dtm.getValueAt(selectedRow, 0).toString();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            String faculty = lfaculty.getSelectedItem().toString();
            String campus = lcampus.getSelectedItem().toString();
            String department = ldep.getSelectedItem().toString();
            String building = lbuilding.getSelectedItem().toString();
            String facultyid="";
            String campusid="";
            String depid="";
            String buildingid="";
            ResultSet rs1 = DB.DB.search("select idfaculty from faculty where name='" + faculty + "'");
            if (rs1.first()) {
                facultyid=rs1.getString(1);
            }
            ResultSet rs2 = DB.DB.search("select idcampus from campus where name='" + campus + "'");
            if (rs2.first()) {
                campusid=rs2.getString(1);
            }
            ResultSet rs3 = DB.DB.search("select iddepartment from department where name='" + department + "'");
            if (rs3.first()) {
                depid=rs3.getString(1);
            }
            
            ResultSet rs4 = DB.DB.search("select idbuilding from building where name='" + building + "'");
            if (rs4.first()) {
                buildingid=rs4.getString(1);
            }
            DB.DB.iud("update lecturer set name='"+lecname.getText()+"', emp_id='"+lempid.getText()+"', rank='"+lrank.getText()+"', faculty_id='"+facultyid+"', department_id='"+depid+"', campus_id='"+campusid+"', building_id='"+buildingid+"', level_id='"+llevel.getSelectedItem().toString()+"' where idlecturer='"+lecid+"'");
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
            loadTableData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try {
            DB.DB.iud("delete from lecturer where idlecturer='"+lecid+"'");
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTableData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managelecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managelecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managelecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managelecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managelecturers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lbuilding;
    private javax.swing.JComboBox<String> lcampus;
    private javax.swing.JComboBox<String> ldep;
    private javax.swing.JTextField lecname;
    private javax.swing.JTextField lempid;
    private javax.swing.JComboBox<String> lfaculty;
    private javax.swing.JComboBox<String> llevel;
    private javax.swing.JTextField lrank;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void loadFaculty() {
        try {
            ResultSet rs = DB.DB.search("select distinct name from faculty");
            while (rs.next()) {
                lfaculty.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadCampus() {
        try {
            ResultSet rs = DB.DB.search("select distinct name from campus");
            while (rs.next()) {
                lcampus.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadLevel() {
        try {
            ResultSet rs = DB.DB.search("select distinct level from level");
            while (rs.next()) {
                llevel.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadDepartment() {
        try {
            ResultSet rs = DB.DB.search("select distinct name from department");
            while (rs.next()) {
                ldep.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void loadBuilding() {
        try {
            ResultSet rs = DB.DB.search("select distinct name from building");
            while (rs.next()) {
                lbuilding.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    private void clearFields() {
        lecname.setText("");
        lempid.setText("");
        lrank.setText("");
    }

    private void loadTableData() {
        try {
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.DB.search("select l.idlecturer,l.name,l.emp_id,f.name,d.name,c.name,b.name,l.level_id,l.rank from lecturer l JOIN building b on l.building_id=b.idbuilding JOIN campus c on l.campus_id=c.idcampus JOIN department d on l.department_id=d.iddepartment JOIN faculty f on l.faculty_id=f.idfaculty");
            while (rs.next()) {                
                Vector v=new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
